repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
    exclude: "mkdocs.yml"
  - id: end-of-file-fixer
    exclude: "(.*.svg)|(tests/data/mgf/.*.mgf)"
  - id: trailing-whitespace
    exclude: "(tests/data/mgf/.*.mgf)"
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.48
  hooks:
    - id: lint
- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
    - id: black
      language_version: python3.8
- repo: https://github.com/keewis/blackdoc
  rev: v0.3.7
  hooks:
    - id: blackdoc
- repo: https://github.com/asottile/pyupgrade
  rev: v2.38.2
  hooks:
  - id: pyupgrade
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/PyCQA/autoflake
  rev: v1.6.1
  hooks:
  - id: autoflake
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-black
    - mdformat-sentencebreak
    - mdformat-frontmatter
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.1  # add version here
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
- repo: local
  hooks:
  - id: pydocstringformatter
    name: pydocstringformatter
    entry: poetry run pydocstringformatter elfragmentador
    language: system
    always_run: true
    include: ".*.py"
  - id: pytest
    name: pytest-check
    entry: poetry run python -m pytest -x
    language: system
    pass_filenames: false
    always_run: true
#   - id: build_docs
#     name: build_docs
#     entry: poetry run python -m mkdocs build --strict
#     language: system
#     pass_filenames: false
#     always_run: true
