site_name: ms2ml Docs

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - ms2ml


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: true
            docstring_style: google
            line_length: 120
            members_order: source
            show_if_no_docstring: true
            show_signature_annotations: true
            annotations_path: source
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
