site_name: ms2ml Docs

theme:
  name: material

markdown_extensions:

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - ms2ml


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      docstring_style: numpy
