
name: CI Testing

on:
  pull_request:
  push:
    branches: [ main, devel, release ]
  schedule:
  - cron: "4 5 4 1/1 *" # Run monthly.

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      # Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Debug Info
        run: echo ${{ github.ref }} ${{ github.event_name }} ${{ endsWith(github.ref, 'heads/release') && (github.event_name == 'push') }}
        # refs/heads/main push false is the output of the main branch when tagged with a release ...

      - name: View Python --version
        run: python --version

      # Poetry Setup
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: '1.2.0'

      - name: View poetry --version
        run: poetry --version
      - name: Install Stuff
        run: poetry install --no-root --only lint

      # Linting
      - name: Black
        run: poetry run python -m black . --check --diff
      - name: ruff
        run: poetry run ruff .
      - name: isort
        run: poetry run isort . --check

  ci:
    runs-on: 'ubuntu-latest'
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        poetry-version: ['1.2.0',]
        experimental: [false]
        include:
          - python-version: '3.11-dev'
            poetry-version: '1.2.0'
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:

      # Initial Setup
      - uses: actions/checkout@v3

      # Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: View Python --version
        run: python --version

      # Poetry Setup
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --version
        run: poetry --version

      # Package Setup
      - name: Install deps
        run: poetry install --no-interaction --verbose --extras test --extras docs

      # CI checks
      - name: Pytest
        run: poetry run python -m pytest --cov . --cov-report=xml

      # Documentation setup
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: View Quarto version
        run:
          quarto --version

      - name: mkdocs
        run: poetry run python -m mkdocs build --strict

      # Upload coverage
      - uses: codecov/codecov-action@v3
        with:
          verbose: true # optional (default = false)



  release:
    # Run when there is a new push on the release branch
    runs-on: 'ubuntu-latest'
    needs: ci
    if: endsWith(github.ref, 'heads/release') && (github.event_name == 'push')
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

      # Documentation setup
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: View Quarto version
        run:
          quarto --version

      # Python setup
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: View Python --version
        run: python --version

      # Poetry Setup
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: '1.2.0'
      - name: View poetry --version
        run: poetry --version

      # Package Setup
      - name: Install deps
        run: poetry install -n -v --all-extras

      - name: Build package
        run: |
          poetry build

      # Publishing Docs
      - name: Deploy Docs
        env:
            GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          poetry run python -m mkdocs gh-deploy --strict --force

      # Publish Package
      - name: Publish Setup
        env:
          PYPITOKEN: ${{ secrets.PYPITOKEN }}
        run: |
          poetry config pypi-token.pypi ${PYPITOKEN}
      - name: Publish
        run: |
          poetry publish --no-interaction
